export const NEXT_STEP = 'NEXT_STEP'
export const PREV_STEP = 'PREV_STEP'
export const CURRENT_NAME = 'CURRENT_NAME'
export const SET_TASKS = 'SET_TASKS'
export const SET_RESOURCES = 'SET_RESOURCES'
export const SET_PLAN = 'SET_PLAN'
